-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NULL,
    `password` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Expense` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `amount` INTEGER NOT NULL DEFAULT 0,
    `note` VARCHAR(191) NOT NULL DEFAULT '',
    `paymentType` ENUM('CASH', 'CREDIT_CARD', 'DEBIT_CARD') NOT NULL DEFAULT 'CASH',
    `expenseType` ENUM('GROCERIES', 'SNACKS', 'EATING_OUT', 'COFFEE', 'DRINKS', 'CLOTHING', 'ENTERTAINMENT', 'SUBSCRIPTION', 'TRAVEL', 'OTHER') NOT NULL DEFAULT 'OTHER',
    `date` DATE NOT NULL,
    `time` TIME NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Expense` ADD CONSTRAINT `Expense_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
